name: jupyterlite-webr-kernel
channels:
  - conda-forge
dependencies:
  # python
  - python
  # - build
  - pip
  - ruff
  # javascript
  - nodejs=20
  # deps
  - jupyterlab >=4.0,<5
  - jupyterlite-core >=0.4.0
